# 开发测试的服务环境快速搭建
version: '3.8'

services:

  #mysql服务
  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
  #mysql管理客户端adminer
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 6082:8080
  #mysql管理客户端phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 6084:80
    volumes:
    - ./phpmyadmin/sessions:/sessions

  #MongoDB服务
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongodb/log:/var/log/mongodb/
      - ./mongodb/db:/data/db
  #mongoDB管理客户端mongo-express
  mongo-express:
    links: 
      - mongo
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - 6081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123456

  #Redis服务
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    command: 
      redis-server --port 6379 --requirepass 123456  --appendonly yes
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/etc/redis/redis.conf
  #redis管理客户端redis-commander
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
    - REDIS_HOST=redis
    - REDIS_PASSWORD=123456
    ports:
    - "6083:8081"